spring:
  jpa:
    database: mysql
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/questionnaire
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver